### ISSUE TITLE
Question - ViewModel - DTO - Model

### ISSUE THREAD

**Issue by jzeferino** [RobGibbens/DtoToVM#2]
In this example, in your ViewModel you get the DTO from the webService and then you map them to the Model and return it to be used by the View.

In my opinion the View Should use DTO, and the Model is only used to store \ retrieve the information from the database.

Can you please share you opinion about this @RobGibbens .

**Comment by RobGibbens** [comment]
@jzeferino I view the DTO as the boundary between my app and the remote web service. It's the definition of the return values from the remote service, and as such it has the potential to change.  In this case, I control the web service, but there are times where that might not be true. Even if some other company is controlling the web service, I will still need the DTO to adhere to the shape of the service in order to deserialize it.  So, the DTO is volatile, and I don't want the rest of the my app to depend on it.  That's why my ViewModels, and hence my screens, don't have a tight coupling to the DTO but instead depend on the Model.

I don't show it in this sample, but I actually take it a step further usually, and I don't have my View depend on the Model either, but instead just map from the Model to the ViewModel. That way, the View only ever depends on the ViewModel.  For example, say I had a database table with 80 columns on it, and therefore a Model with 80 properties on it.  I'd never want to query all that and make all that accessible to my Views. Instead, I'd query for _just the data that the view needs_ and return just that in the ViewModel.

As with anything in software though, what's right for one app may not be right for another.  You should always make your architectural decisions based on what's right for you.  If you're ok showing the DTOs on the View, then that's your choice.

I hope this helps explain my thinking.  Thanks!
